### ISSUE TITLE
Я правильно помню, что пул-реквесты надо в ветку dev отправлять?

### ISSUE THREAD

**Issue by SergeR** [webasyst/webasyst-framework#100]
:question: Кажется, где-то видел объявление на эту тему, но не помню где. :grin:

**Comment by WinterSilence** [comment]
Ну обычно так все и работают: сначало подаются запросы в dev, после их проверки и утверждения переносят в master

**Comment by SergeR** [comment]
:smile: тут могут быть свои правила

**Comment by SergeR** [comment]
Судя по репозиторию Shopscript, сами авторы предпочитают сразу в master. Но pr в dev тоже принимают. 😀 Будем подавать пример 😎

**Comment by alexmuz** [comment]
Неправда, с момента появления ветки dev, всё сначала туда, а потом уже в master.
Иногда (как сегодня) просто это происходит почти одновременно.

Вывод: все пулл-реквесты отправлять в ветку dev.
