### ISSUE TITLE
Добавить приложение installer в репозиторий

### ISSUE THREAD

**Issue by WinterSilence** [webasyst/webasyst-framework#105]
Столкнулся с [проблемой](https://github.com/webasyst/webasyst-framework/pull/104), для её исправления логичнее было бы внести правки в стили  installer'а, но из-за его отсутствия в репозитории приходится править основные стили, а это может повлечь за собой проблемы с отображением в других приложениях.

**Comment by alexmuz** [comment]
Здесь никогда не было, нет и не будет приложения инсталлер.
Инсталлер - приложение, с помощью которого можно обновить код.
Здесь же github и обновлять код предполагается средствами git.
