### ISSUE TITLE
Отсутствует wa-installer

### ISSUE THREAD

**Issue by Grebennik** [webasyst/webasyst-framework#228]
Здравствуйте.
Не вижу в репозитории wa-installer, соответственно не запускается скрипт установки на сервере.

**Comment by Leonix** [comment]
Скрипт установки и приложение Инсталлер конфликтуют с гитом. Так задумано, что если установка ставится из этого репозитория, она и обновляться должна механизмами гита.

Инструкцию по установке см. в README.markdown
