### ISSUE TITLE
Баг в webasystBackendCheatSheetActions::getBlocks()

### ISSUE THREAD

**Issue by WinterSilence** [webasyst/webasyst-framework#291]
https://github.com/webasyst/webasyst-framework/blob/e86eeacb9fbb22284511cefe916e74e44eb68c6a/wa-system/webasyst/lib/actions/backend/webasystBackendCheatSheet.actions.php#L210
переменная не определена.

**Comment by Miksser** [comment]
Fix. Tnx

**Comment by WinterSilence** [comment]
@Miksser что-то не заметил изменений

**Comment by tintw** [comment]
@WinterSilence выйдет в ближайшем релизе.
