### ISSUE TITLE
Ошибка при использовании UI 2.0

### ISSUE THREAD

**Issue by WinterSilence** [webasyst/webasyst-framework#356]
И так во многих приложениях использующих UI 2.0
![изображение](https://user-images.githubusercontent.com/3521094/162416381-bce455e7-9637-4003-b5cb-4bddcc4c12ed.png)

![изображение](https://user-images.githubusercontent.com/3521094/162416205-3135f494-a3a9-4d5b-9fbe-bb2990daf368.png)

**Comment by WinterSilence** [comment]
@mikeushenin наоборот тени перекрываются белым фоном

**Comment by mikeushenin** [comment]
Разработчики Webasyst не увидели никакой проблемы на ваших снимках. Судя по всему, всё работает так, как и было задумано.

**Comment by WinterSilence** [comment]
@mikeushenin такое себе дизайнерское решение, в темном режиме шапка основной контент и шапка имеют разный цвет фона, в светлом режиме контент и шапка используют одинаковый цвет фона и сливаются. + обрубок тени в сайдбаре выглядит странновато.
