### ISSUE TITLE
Визуальный редактор: странная работа с мышью и клавиатурой

### ISSUE THREAD

**Issue by SergeR** [webasyst/webasyst-framework#45]
Внезапно, в визуальном режиме, перестает реагировать на клики мышью (невозможно передвинуть курсор, выделить текст). Также перестает реагировать на стрелки клавиатуры — вверх-вниз работают, а вправо-влево нет. Точную последовательность действий, приводящую к такому эффекту пока не выявил. :disappointed_relieved: 

Бразеры: Chrome/Win8; Chromium/Ubuntu, Firefox 26/Ubuntu

**Comment by alexmuz** [comment]
В последних версия вроде не наблюдается больше.
Если воспроизведёте, то нужна последовательность действий после которых это происходит.
