### ISSUE TITLE
final?

### ISSUE THREAD

**Issue by SergeR** [webasyst/webasyst-framework#66]
В свете вчерашних обсуждений о том, что нельзя авторам плагинов напрямую залезать в сессию. :smile: 

Вот возьмем класс `waLogModel`. (https://github.com/webasyst/webasyst-framework/blob/master/wa-system/webasyst/lib/models/waLog.model.php#L3) Вообще плагины туда писать, похоже, не могут (почему? или я ошибаюсь) и не должны. Но можно заэкстендить этот класс и перегрузить метод или написать свой для добавления строки в лог. Тогда мой плагин сможет прикидываться приложением и добавлять события в лог.

Или все-таки прислать Pull-request чтобы это был `final class` ? :smile:

**Comment by alexmuz** [comment]
Даже если его сделать final то никто не помешает плагину либо просто напрямую вставить запись, либо использовать стандартный метол insert

Так что final вообще никак не решает обозначенную проблему.

Теоретически плагин может сделать:
```
$model  = new waModel();
$model->exec('DROP TABLE wa_contact');
```
и всё сломается...
На мой взгляд, это не задача фреймворка бороться с подобным.
