### ISSUE TITLE
Проверять при установке наличие функции hash()

### ISSUE THREAD

**Issue by SergeR** [webasyst/webasyst-framework#71]
На некоторых популярных хостингах, [например RU-CENTER](http://forum.nic.ru/showthread.php?t=6469), модуль с этой функцией по умолчанию отключен. Эта функция жизненно необходима для хеширования паролей. :)

Нужно проверять хотя бы в Инсталлере на одном из этапов установки.

**Comment by SergeR** [comment]
Похоже, что `crypt()` зависит от системы и конкретной версии PHP. Это чревато невозможностью или трудностями переноса с одного хостинга на другой. Миграция, например из "облака Webasyst" на отдельный хостинг или просто смена хостинга — достаточно частое явление.

**Comment by SergeR** [comment]
В [документации](http://www.webasyst.ru/developers/docs/tips/security/) об этом не сказано, но для хранения хэша пароля в БД используется поле длиной 32 символа. Видимо, заточено под дефолтный `md5()` (правда, тогда непонятно, почему оно `VARCHAR(32)` а не `CHAR(32)`, но не суть). Поэтому попытки хэшировать пароли просто с помощью `hash('sha256',$password . $salt)` обречены. надо обязательно `md5(hash('sha256',$password . $salt))`. То есть `md5()` должна обязательно выступать "оберткой".

**Comment by WinterSilence** [comment]
> Похоже, что crypt() зависит от системы и конкретной версии PHP.

Так и hash аналогично заточена, hash как следует даже из назания ориентирована на несколько другие цели, для паролей разрабы php рекомендуют crypt

> Видимо, заточено под дефолтный md5()

Не обязательно md5 http://php.net/manual/ru/function.hash.php#104987 ,но неплохо бы увеличить размер поля до 128

**Comment by WinterSilence** [comment]
@SergeR перечитывал мануал и вспомнил эту тему

> Другой возможностью является функция crypt(), которая поддерживает несколько алгоритмов хэширования в PHP 5.3 и новее. При использовании этой функции вы можете быть уверенным, что выбранный вами алгоритм доступен, так как PHP содержит собственную реализацию каждого поддерживаемого алгоритма, даже в случае, если какие-то из них не поддерживаются вашей системой. 

Т.ч. никаких проблем

**Comment by alexmuz** [comment]
Поле password уже VARCHAR(128)
Наличие hash в системные требования добавим в ближайшее время.
