### ISSUE TITLE
Предложение по переходу на фреймворк Symfony

### ISSUE THREAD

**Issue by uelnur** [webasyst/webasyst-framework#79]
Советую ознакомиться с фреймворком Симфони, так как он мощный и современный фреймворк. На нем уже многое реализовано, очень профессионально. Думаю, можно написать отличный CMS на symfony, с идеями ShopScripta.

http://symfony.com/doc/current/book/index.html

**Comment by WinterSilence** [comment]
@uelnur жжошь! плюсую тему! )))
