### ISSUE TITLE
Добавить теги и ветки в репозиторий

### ISSUE THREAD

**Issue by nikitinsm** [webasyst/webasyst-framework#85]
Не хватает тегов с детализацией версий 1.0.0, 1.0.1 и т.д.
ветки master и production

**Comment by alexmuz** [comment]
Была добавлена ветка dev, в которую будут выкладываться все коммиты до официального релиза.
В мастер (в которой будет официальная последняя версия) отныне все изменения будут попадать только из ветки dev.

Теги для релизов тоже в скором времени появятся.
